[NX]
; необязательно: путь к NX выбирается лаунчером, но можно хранить для истории
BaseDir=

[Scan]
Root=D:\ZherlitsynEE\SaveFormatTest\Test\PRT
; можно несколько Root= (повторять строку)
IncludeFolderName=Кронштейны
; можно несколько IncludeFolderName= (повторять строку)
Mode=ScanAndExport          ; или ScanOnly
DbPath=D:\ZherlitsynEE\NxPrtAttributeScanner\cache\parts.db

[Excel]
Out=D:\ZherlitsynEE\NxPrtAttributeScanner\reports\Parts.xlsx
GroupSheets=1               ; 1/0
GroupMode=FirstLevel        ; FirstLevel или AllInOne